apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales-api
  template:
    metadata:
      labels:
        app: sales-api
    spec:
      containers:
      - name: sales-api
        image: docker pull ghcr.io/anuruddhak91/devops-challenge-dotnet:main  
        ports:
        - containerPort: 5000
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: CONNECTION_STRING
          value: ${{ secrets.CONNECTION_STRING }}
