---
name: Deploy

on:
  workflow_dispatch:

jobs:
  db-migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '5.0.x'

      - name: Restore dependencies
        run: dotnet restore src/DevOpsChallenge.SalesApi.Database/DevOpsChallenge.SalesApi.Database.csproj

      - name: Apply database migrations
        env:
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
        run: dotnet ef database update --project src/DevOpsChallenge.SalesApi.Database/DevOpsChallenge.SalesApi.Database.csproj

  deploy:
    runs-on: ubuntu-latest
    needs: db-migrations
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -k ./k8s/overlays/prod
